### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by Plazmaz** [Thecakeisgit/DuckuinoPlus#1]
I thought it might be worth suggesting adding a gh-pages branch, which can mirror master. This would allow for the project to be live at thecakeisgit.github.io/DuckuinoPlus/

**Comment by Thecakeisgit** [comment]
It's a good idea, ill do this now :D

**Comment by Thecakeisgit** [comment]
Done : https://thecakeisgit.github.io/DuckuinoPlus/
